---
abstract: 'PX Pay Interface for www.paymentexpress.com'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-PxPay
requires:
  LWP::UserAgent: 0
  Net::SSLeay: 0
  XML::Simple: 0
resources:
  repository: git://github.com/fayland/business-pxpay.git
version: 0.04
